<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>
</Project>
